INSERT INTO article (title, content, stock_ticker, created_at, updated_at) VALUES ('제목 1', '내용 1', '005930',NOW(), NOW())
INSERT INTO article (title, content, stock_ticker, created_at, updated_at) VALUES ('제목 2', '내용 2', '005930', NOW(), NOW())
INSERT INTO article (title, content, stock_ticker, created_at, updated_at) VALUES ('제목 3', '내용 3', '005930', NOW(), NOW())
INSERT INTO article (title, content, stock_ticker, created_at, updated_at) VALUES ('제목 1', '내용 1', '034020', NOW(), NOW())
INSERT INTO article (title, content, stock_ticker, created_at, updated_at) VALUES ('제목 2', '내용 2', '034020', NOW(), NOW())
INSERT INTO article (title, content, stock_ticker, created_at, updated_at) VALUES ('제목 1', '내용 1', '010140', NOW(), NOW())
INSERT INTO article (title, content, stock_ticker, created_at, updated_at) VALUES ('제목 2', '내용 2', '010140', NOW(), NOW())
